spring: #???? ??
  datasource: #???? 2?
    url: jdbc:h2:tcp://localhost/~/soccerV2 #4?
    username: soccerV2
    password: soccerV2
    driver-class-name: org.h2.Driver
  jpa:
    hibernate: #???? 4?
      ddl-auto: #create
    properties: #???? 4?
      hibernate: #???? 6?

