spring: #???? ??
  datasource: #???? 2?
    url: jdbc:h2:tcp://localhost/~/SoccerV2 #4?
    username: SoccerV2
    password: SoccerV2
    driver-class-name: org.h2.Driver
  jpa:
    hibernate: #???? 4?
      ddl-auto: create
    properties: #???? 4?
      hibernate: #???? 6?
      format_sql: true

#logging.level:
#  org.hibernate.SQL: debug
## org.hibernate.type: trace